"""Add admin_users, agent_accounts, and audit_log_entries tables.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-07

Adds the Milestone 0 auth/audit foundation: ``AdminUser`` (human
session-login accounts), ``AgentAccount`` (named, API-key-authenticated AI
agent integrations), and ``AuditLogEntry`` (append-only actor-attributed
change log). Autogenerated against a live Postgres instance via ``alembic
revision --autogenerate``, then hand-edited to add explicit ``DROP TYPE``
statements for the two native Postgres enums on downgrade (Alembic's
autogenerate does not emit these itself, which would otherwise leak the
enum types across a downgrade/upgrade cycle).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "admin_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("admin", "scanner", name="admin_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_users_email"), "admin_users", ["email"], unique=True)

    op.create_table(
        "agent_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("created_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_agent_accounts_key_hash"), "agent_accounts", ["key_hash"], unique=True)

    op.create_table(
        "audit_log_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_type", sa.Enum("human", "ai_agent", name="actor_type"), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_name", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("target_type", sa.String(length=100), nullable=True),
        sa.Column("target_id", sa.String(length=255), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_entries_action"), "audit_log_entries", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_log_entries_created_at"), "audit_log_entries", ["created_at"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_audit_log_entries_created_at"), table_name="audit_log_entries")
    op.drop_index(op.f("ix_audit_log_entries_action"), table_name="audit_log_entries")
    op.drop_table("audit_log_entries")

    op.drop_index(op.f("ix_agent_accounts_key_hash"), table_name="agent_accounts")
    op.drop_table("agent_accounts")

    op.drop_index(op.f("ix_admin_users_email"), table_name="admin_users")
    op.drop_table("admin_users")

    # Postgres native enums aren't dropped automatically when their last
    # referencing table is dropped — clean them up explicitly so a
    # downgrade/upgrade cycle doesn't fail on "type already exists".
    sa.Enum(name="actor_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="admin_role").drop(op.get_bind(), checkfirst=True)
