"""Add events, event_configs, shows, and ticket_types tables.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-07

Adds the Milestone 1 "Backoffice core" schema: ``Event`` (top-level
container, draft/published + manual sales-pause), ``EventConfig`` (1:1,
SMTP/Mollie/invoice settings — secrets encrypted at rest via
``EncryptedString``), ``Show`` (belongs to Event), and ``TicketType``
(belongs to Show). Autogenerated against a live Postgres instance via
``alembic revision --autogenerate``, then hand-edited to: add the missing
``app.core.crypto`` import for ``EncryptedString`` columns, rename to this
project's ``NNNN_description`` revision-file convention, and add explicit
``DROP TYPE`` statements for the three native Postgres enums on downgrade
(mirrors ``0002``'s handling of this same autogenerate limitation).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app.core.crypto

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "events",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.Enum("draft", "published", name="publish_status"), nullable=False),
        sa.Column("sales_paused", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_slug"), "events", ["slug"], unique=True)

    op.create_table(
        "event_configs",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("smtp_host", sa.String(length=255), nullable=True),
        sa.Column("smtp_port", sa.Integer(), nullable=True),
        sa.Column(
            "smtp_encryption",
            sa.Enum("none", "ssl", "starttls", name="smtp_encryption_mode"),
            nullable=False,
        ),
        sa.Column("smtp_username", sa.String(length=255), nullable=True),
        sa.Column("smtp_password", app.core.crypto.EncryptedString(length=2048), nullable=True),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("sender_email", sa.String(length=255), nullable=True),
        sa.Column("mollie_test_api_key", app.core.crypto.EncryptedString(length=2048), nullable=True),
        sa.Column("mollie_live_api_key", app.core.crypto.EncryptedString(length=2048), nullable=True),
        sa.Column("invoice_company_name", sa.String(length=255), nullable=True),
        sa.Column("invoice_company_address", sa.Text(), nullable=True),
        sa.Column("invoice_company_vat_number", sa.String(length=50), nullable=True),
        sa.Column("invoice_number_prefix", sa.String(length=50), nullable=True),
        sa.Column("sales_live_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "enabled_payment_methods",
            sa.ARRAY(sa.Enum("mollie", "door", name="payment_method")),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )

    op.create_table(
        "shows",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("doors_time", sa.Time(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("venue_name", sa.String(length=255), nullable=False),
        sa.Column("venue_address", sa.Text(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("draft", "published", name="publish_status"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shows_event_id"), "shows", ["event_id"], unique=False)

    op.create_table(
        "ticket_types",
        sa.Column("show_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("service_fee_included", sa.Boolean(), nullable=False),
        sa.Column("quantity_available", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["show_id"], ["shows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticket_types_show_id"), "ticket_types", ["show_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_ticket_types_show_id"), table_name="ticket_types")
    op.drop_table("ticket_types")

    op.drop_index(op.f("ix_shows_event_id"), table_name="shows")
    op.drop_table("shows")

    op.drop_table("event_configs")

    op.drop_index(op.f("ix_events_slug"), table_name="events")
    op.drop_table("events")

    # Postgres native enums aren't dropped automatically when their last
    # referencing table/column is dropped — clean them up explicitly so a
    # downgrade/upgrade cycle doesn't fail on "type already exists".
    sa.Enum(name="payment_method").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="smtp_encryption_mode").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="publish_status").drop(op.get_bind(), checkfirst=True)
