"""Add themes table.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-07

Adds the Milestone 1.5 "Event Theming" schema: ``Theme`` (1:1 with
``Event``, cascade-deleted with it — fixed color/logo/background/font
fields, optional sanitized ``custom_css``, and a ``publish_status``
draft/published status shared with ``Event``/``Show``). Autogenerated
against a live Postgres instance via ``alembic revision --autogenerate``,
then hand-edited to: rename to this project's ``NNNN_description``
revision-file convention, and add an explicit ``DROP TYPE`` for the new
``theme_font`` native Postgres enum on downgrade (mirrors ``0002``/``0003``'s
handling of this same autogenerate limitation). ``publish_status`` is
reused from ``0003`` (already exists) and is deliberately NOT dropped on
this migration's downgrade — ``events``/``shows`` still depend on it.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "themes",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("primary_color", sa.String(length=7), nullable=False),
        sa.Column("secondary_color", sa.String(length=7), nullable=False),
        sa.Column("accent_color", sa.String(length=7), nullable=False),
        sa.Column("logo_path", sa.String(length=512), nullable=True),
        sa.Column("background_image_path", sa.String(length=512), nullable=True),
        sa.Column(
            "font_choice",
            sa.Enum(
                "system-sans",
                "system-serif",
                "inter",
                "roboto",
                "open-sans",
                "lora",
                "merriweather",
                "playfair-display",
                name="theme_font",
            ),
            nullable=False,
        ),
        sa.Column("custom_css", sa.Text(), nullable=True),
        # `create_type=False`: this enum was already created by 0003 for
        # events.status/shows.status — unlike a fresh Enum in a single
        # migration (where SQLAlchemy's `checkfirst` covers repeated use
        # within the same `upgrade()`), a *new* migration script reusing an
        # existing Postgres enum type by name must say so explicitly, or
        # `CREATE TYPE` is re-attempted and fails with "type already
        # exists".
        sa.Column(
            "status",
            postgresql.ENUM("draft", "published", name="publish_status", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )


def downgrade() -> None:
    op.drop_table("themes")

    # Postgres native enums aren't dropped automatically when their last
    # referencing column is dropped — clean up the enum this migration
    # introduced. NOT dropping ``publish_status``: it was created by 0003
    # and is still used by ``events.status``/``shows.status``.
    sa.Enum(name="theme_font").drop(op.get_bind(), checkfirst=True)
