"""Add orders, tickets tables and events.preview_token.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-07

Adds the Milestone 2 "Public site" schema:

- ``events.preview_token`` — the unguessable, high-entropy token that makes
  a draft Event (and everything nested under it) viewable via the
  ``/preview/{token}/...`` route while still draft (see
  ``app.models.event.Event.preview_token`` docstring). Added as nullable,
  backfilled per-row with a fresh random token (there's no single column
  default that could produce a *distinct* value per existing row), then
  made ``NOT NULL`` with a unique index — mirrors ``events.slug``'s
  unique-index convention from 0003.
- ``orders`` — one buyer's purchase (``order_status`` is a new native enum;
  ``payment_method`` reuses the existing one from 0003, so
  ``create_type=False``).
- ``tickets`` — one physical ticket per row (see
  ``app.models.ticket.Ticket`` docstring for why these are created at
  checkout time rather than in Milestone 4). ``ticket_type_id`` is
  ``ON DELETE RESTRICT`` (deliberately NOT cascade, unlike every other FK
  in this schema so far) so a TicketType with sold tickets can't be
  deleted out from under real Orders.

Hand-written (not autogenerated) to get the ``preview_token`` backfill
loop right; follows this project's ``NNNN_description`` revision-file
convention and explicit ``DROP TYPE`` handling for the new native enum on
downgrade, same as every prior migration in this series.
"""

import secrets
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- events.preview_token ---
    op.add_column("events", sa.Column("preview_token", sa.String(length=64), nullable=True))
    bind = op.get_bind()
    event_ids = bind.execute(sa.text("SELECT id FROM events")).scalars().all()
    for event_id in event_ids:
        bind.execute(
            sa.text("UPDATE events SET preview_token = :token WHERE id = :id"),
            {"token": secrets.token_urlsafe(32), "id": event_id},
        )
    op.alter_column("events", "preview_token", nullable=False)
    op.create_index(op.f("ix_events_preview_token"), "events", ["preview_token"], unique=True)

    # --- orders ---
    op.create_table(
        "orders",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("buyer_name", sa.String(length=255), nullable=False),
        sa.Column("buyer_email", sa.String(length=255), nullable=False),
        sa.Column("buyer_address", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "paid", "cancelled", "expired", "pending_door", name="order_status"),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            postgresql.ENUM("mollie", "door", name="payment_method", create_type=False),
            nullable=False,
        ),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_event_id"), "orders", ["event_id"], unique=False)
    op.create_index(op.f("ix_orders_buyer_email"), "orders", ["buyer_email"], unique=False)

    # --- tickets ---
    op.create_table(
        "tickets",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("ticket_type_id", sa.UUID(), nullable=False),
        sa.Column("qr_token", sa.String(length=255), nullable=True),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scanned_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ticket_type_id"], ["ticket_types.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["scanned_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("qr_token"),
    )
    op.create_index(op.f("ix_tickets_order_id"), "tickets", ["order_id"], unique=False)
    op.create_index(op.f("ix_tickets_ticket_type_id"), "tickets", ["ticket_type_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_tickets_ticket_type_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_order_id"), table_name="tickets")
    op.drop_table("tickets")

    op.drop_index(op.f("ix_orders_buyer_email"), table_name="orders")
    op.drop_index(op.f("ix_orders_event_id"), table_name="orders")
    op.drop_table("orders")

    op.drop_index(op.f("ix_events_preview_token"), table_name="events")
    op.drop_column("events", "preview_token")

    # order_status is new in this migration; payment_method is reused from
    # 0003 and must NOT be dropped here (still used by event_configs).
    sa.Enum(name="order_status").drop(op.get_bind(), checkfirst=True)
