"""Add EventConfig.mollie_mode and orders.mollie_payment_id.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-08

Adds the Milestone 3 "Payments" schema:

- ``event_configs.mollie_mode`` — a new native enum (``mollie_mode``:
  ``test``/``live``), the explicit per-event admin toggle for which of
  ``EventConfig``'s two Mollie API keys is actually used at checkout (see
  ``app.models.event_config.EventConfig.mollie_mode`` docstring). Not
  nullable, defaulting to ``test`` so an existing (or newly created)
  EventConfig can never accidentally start processing real charges.
- ``orders.mollie_payment_id`` — the Mollie payment id returned by Mollie's
  Create Payment API, nullable (only set for real ``mollie``-method orders,
  never for ``door`` orders or the preview-mode simulated-payment path) and
  unique + indexed (it's the lookup key the webhook handler uses to find an
  Order from a Mollie webhook's payment id — see
  ``app.api.routes.public.mollie_webhook``).

Hand-written (not autogenerated), following this project's ``NNNN_
description`` revision-file convention and explicit ``DROP TYPE`` handling
for the new native enum on downgrade, same as every prior migration in this
series.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_mollie_mode_enum = sa.Enum("test", "live", name="mollie_mode")


def upgrade() -> None:
    _mollie_mode_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "event_configs",
        sa.Column("mollie_mode", _mollie_mode_enum, nullable=False, server_default="test"),
    )
    # Drop the server_default once existing rows are backfilled — the ORM
    # model supplies the Python-side default for new rows going forward
    # (mirrors this project's convention elsewhere of not leaving a
    # permanent DB-level default once it's only needed for the backfill).
    op.alter_column("event_configs", "mollie_mode", server_default=None)

    op.add_column("orders", sa.Column("mollie_payment_id", sa.String(length=255), nullable=True))
    op.create_index(
        op.f("ix_orders_mollie_payment_id"), "orders", ["mollie_payment_id"], unique=True
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_orders_mollie_payment_id"), table_name="orders")
    op.drop_column("orders", "mollie_payment_id")

    op.drop_column("event_configs", "mollie_mode")
    _mollie_mode_enum.drop(op.get_bind(), checkfirst=True)
